### ISSUE TITLE
Double semicolons in SCSS maps.

### ISSUE THREAD

**Issue by Val-Git** [g-plane/malva#10]
When running `dprint fmt` Malva adds additional semicolons in SCSS maps.

I need to keep my maps multi-line and I add an ignore comment to them. But Malva has a side effect: in this case, it adds second semicolons at the end of the maps.

input:
```scss
// malva-ignore
$padding: map.get((
  sm: 4px,
  md: 8px,
  lg: 12px
), lg);

// malva-ignore
$size: (
  sm: 16px,
  md: 24px
);
```
output:
```scss
// malva-ignore
$padding: map.get((
  sm: 4px,
  md: 8px,
  lg: 12px
), $size);;

// malva-ignore
$size: (
  sm: 16px,
  md: 24px
);;
```

By the way, it would be great if Malva allowed specifying multi-line maps, for example through the config.

**Comment by g-plane** [comment]
Can you open a new issue about multi-line maps? They're different problems.

**Comment by Val-Git** [comment]
Done [#11](https://github.com/g-plane/malva/issues/11)
