### ISSUE TITLE
Ability to use multi-line maps

### ISSUE THREAD

**Issue by Val-Git** [g-plane/malva#11]
Add the ability to customize Malva's behavior for formatting SCSS maps.

If I write the following code
```scss
$size: (
  sm: 16px,
  md: 24px,
  lg: 32px
);
```
It will be formatted into a one-line map.
```scss
$size: (sm: 16px, md: 24px, lg: 32px);
```
A configuration option such as `mapLinebreak: "always"` would be highly beneficial.
To format the above input to the output (with trailing comma)
```scss
$size: (
  sm: 16px,
  md: 24px,
  lg: 32px,
);
```

**Comment by g-plane** [comment]
My solution is detecting original code layout without any configurations. In other words, if original code is "multi-line", it will be "multi-line".
