### ISSUE TITLE
Support stroustrup code style

### ISSUE THREAD

**Issue by suchverynice** [g-plane/malva#20]
Would you consider adding config option like [dprint-plugin-typescript](https://github.com/dprint/dprint-plugin-typescript/tree/main)'s `nextControlFlowPosition` for SCSS? Will be much appreciated!

**Comment by suchverynice** [comment]
Yup, I understand...

As I'm not a Rust programmer, could you advise:

1. Looking through, I believe these are what I need to change, yes?
    ```diff
    // https://github.com/g-plane/malva/blob/main/malva/src/doc_gen/sass.rs#L395
    - iter::once(Doc::space())
    + iter::once(Doc::hard_line())

    // https://github.com/g-plane/malva/blob/main/malva/src/doc_gen/sass.rs#L415
    - docs.push(Doc::space());
    + docs.push(Doc::hard_line());
    ```
2. Could you advise how to then compile for use and also integrate with dprint?

Thanks in advance!

**Comment by suchverynice** [comment]
ok... if you ever change your mind, it'd be awesome

**Comment by g-plane** [comment]
Sorry, no plans for this style.
