### ISSUE TITLE
Support css order like stylelint-order?

### ISSUE THREAD

**Issue by takkuumi** [g-plane/malva#4]
Support css order like stylelint-order?

**Comment by g-plane** [comment]
Do you mean re-order CSS properties in qualified rule?

**Comment by takkuumi** [comment]
> Do you mean re-ordering CSS properties in qualified rule?

Yeap

**Comment by g-plane** [comment]
It sounds complicated because we may need to understand each properties and their semantic.

**Comment by so1ovu** [comment]
@g-plane hopefully it can be supported 🥹
